
type Staked @entity(immutable: true) {
  id: Bytes!
  staker: Bytes! # address
  stakeId: Bytes! # bytes32
  amount: BigInt! # uint128
  stakeDay: Int! # uint16
  daysLock: Int! # uint16
  flags: Int! # uint16
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type Unstaked @entity(immutable: true) {
  id: Bytes!
  staker: Bytes! # address
  stakeId: Bytes! # bytes32
  unstakeDay: Int! # uint16
  amount: BigInt! # uint128
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type RewardClaimed @entity(immutable: true) {
  id: Bytes!
  user: Bytes! # address
  stakeId: Bytes! # bytes32
  poolId: BigInt! # uint256
  strategyId: BigInt! # uint256
  rewardAmount: BigInt! # uint256
  claimDay: Int! # uint16
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type WalletAggregate @entity(immutable: false) {
  id: ID! # user address
  totalStaked: BigInt!
  lastUpdated: BigInt!
}

type AnnouncePool @entity(immutable: true) {
  id: Bytes!
  poolId: BigInt! # uint256
  startDay: Int! # uint16
  endDay: Int! # uint16
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type PoolUpserted @entity(immutable: true) {
  id: Bytes!
  poolId: BigInt! # uint256
  startDay: Int! # uint16
  endDay: Int! # uint16
  totalPoolWeight: BigInt! # uint256
  parentPoolId: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type StrategyAddedToLayer @entity(immutable: true) {
  id: Bytes!
  poolId: BigInt! # uint256
  layer: BigInt! # uint256
  strategyId: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type StrategyRemovedFromLayer @entity(immutable: true) {
  id: Bytes!
  poolId: BigInt! # uint256
  layer: BigInt! # uint256
  strategyId: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type Pool @entity(immutable: false) {
  id: ID!                  
  startDay: Int!           
  endDay: Int!             
  totalPoolWeight: BigInt! 
  parentPoolId: BigInt!    
  hasAnnounced: Boolean!   
  lastUpdated: BigInt!     
}


type Transfer @entity(immutable: true) {
  id: Bytes!
  from: Bytes! # address
  to: Bytes! # address
  tokenId: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type NFTBalance @entity(immutable: false) {
  id: ID! # wallet address
  count: Int!
  lastUpdated: BigInt!
}

type PoolWeight @entity(immutable: false) {
  id: ID!  # poolId
  poolId: BigInt!
  livePoolWeight: BigInt!
  lastCalculated: BigInt!
  userWeights: [UserPoolWeight!]! @derivedFrom(field: "pool")
}

type UserPoolWeight @entity(immutable: false) {
  id: ID!  # poolId-wallet
  pool: PoolWeight!
  wallet: Bytes!
  stakeWeight: BigInt!
  lastUpdated: BigInt!
}
